Processing contract: /home/jiaming/slither_fp_files/out13908.sol:Divies
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13908.sol:HourglassInterface
Processing contract: /home/jiaming/slither_fp_files/out13908.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13908.sol:UintCompressor
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out13908.sol(289)

[33mWarning[0m for LockedEther in contract 'UintCompressor':
    |*/
    |
  > |library UintCompressor {
    |    using SafeMath for *;
    |    
  at /home/jiaming/slither_fp_files/out13908.sol(227)


