Processing contract: /home/jiaming/slither_fp_files/out14910.sol:F3DKeysCalcShort
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14910.sol:F3Ddatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14910.sol:F3Devents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14910.sol:FoMo3Dthunder
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14910.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14910.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out14910.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14910.sol:modularThunder
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'F3DKeysCalcShort':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library F3DKeysCalcShort {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out14910.sol(1653)

[33mWarning[0m for LockedEther in contract 'F3Ddatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library F3Ddatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out14910.sol(1579)

[33mWarning[0m for LockedEther in contract 'F3Devents':
    |pragma solidity ^0.4.24;
    |
  > |contract F3Devents {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out14910.sol(3)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |*/
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out14910.sol(1750)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |
    |    /**
  at /home/jiaming/slither_fp_files/out14910.sol(1836)

[33mWarning[0m for LockedEther in contract 'modularThunder':
    |//====================================|=========================================
    |
  > |contract modularThunder is F3Devents {}
    |
    |contract FoMo3Dthunder is modularThunder {
  at /home/jiaming/slither_fp_files/out14910.sol(121)


