Processing contract: /home/jiaming/slither_fp_files/out14555.sol:Divies
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14555.sol:DiviesInterface
Processing contract: /home/jiaming/slither_fp_files/out14555.sol:HourglassInterface
Processing contract: /home/jiaming/slither_fp_files/out14555.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14555.sol:UintCompressor
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out14555.sol(21)

[33mWarning[0m for LockedEther in contract 'UintCompressor':
    |
    |//import "./library/UintCompressor.sol";
  > |library UintCompressor {
    |    using SafeMath for *;
    |    
  at /home/jiaming/slither_fp_files/out14555.sol(126)


