Processing contract: /home/jiaming/slither_fp_files/out12868.sol:GoalbonanzaBookInterface
Processing contract: /home/jiaming/slither_fp_files/out12868.sol:GoalbonanzaInterfaceForForwarder
Processing contract: /home/jiaming/slither_fp_files/out12868.sol:GoalbonanzaPlus
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12868.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12868.sol:RSEvents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12868.sol:RSKeysCalc
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12868.sol:RSdatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12868.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12868.sol:modularGoalbonanzaPlus
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'NameFilter':
    |}
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out12868.sol(1591)

[33mWarning[0m for LockedEther in contract 'RSEvents':
    |pragma solidity ^0.4.24;
    |
  > |contract RSEvents {
    |
    |    // fired whenever a player registers a name
  at /home/jiaming/slither_fp_files/out12868.sol(3)

[33mWarning[0m for LockedEther in contract 'RSKeysCalc':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library RSKeysCalc {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out12868.sol(1519)

[33mWarning[0m for LockedEther in contract 'RSdatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library RSdatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out12868.sol(1459)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out12868.sol(1676)

[33mWarning[0m for LockedEther in contract 'modularGoalbonanzaPlus':
    |//====================================|=========================================
    |
  > |contract modularGoalbonanzaPlus is RSEvents {}
    |
    |contract GoalbonanzaPlus is modularGoalbonanzaPlus {
  at /home/jiaming/slither_fp_files/out12868.sol(111)


