Processing contract: /home/jiaming/slither_fp_files/out13468.sol:KeysCalc
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13468.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13468.sol:POOHMOX
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13468.sol:POOHMOXDatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13468.sol:POOHMOXevents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13468.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out13468.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'KeysCalc':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library KeysCalc {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out13468.sol(1496)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out13468.sol(1572)

[33mWarning[0m for LockedEther in contract 'POOHMOXDatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library POOHMOXDatasets {
    |    
    |    struct EventReturns {
  at /home/jiaming/slither_fp_files/out13468.sol(1440)

[33mWarning[0m for LockedEther in contract 'POOHMOXevents':
    |pragma solidity ^0.4.24;
    |
  > |contract POOHMOXevents {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out13468.sol(3)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |
    |    /**
  at /home/jiaming/slither_fp_files/out13468.sol(1656)


