Processing contract: /home/jiaming/slither_fp_files/out14234.sol:DiviesCTR
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:F3DKeysCalcLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:F3Ddatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:F3Devents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:F3DexternalSettingsInterface
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:FoMo3Dlong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:JIincForwarderInterface
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:modularLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14234.sol:otherFoMo3D
[33mWarning[0m for LockedEther in contract 'F3DKeysCalcLong':
    |// Key Calculations
    |
  > |library F3DKeysCalcLong {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out14234.sol(1656)

[33mWarning[0m for LockedEther in contract 'F3Ddatasets':
    |// Structs
    |
  > |library F3Ddatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out14234.sol(1584)

[33mWarning[0m for LockedEther in contract 'F3Devents':
    |// Events 
    |
  > |contract F3Devents {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out14234.sol(6)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |}
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out14234.sol(1746)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out14234.sol(1832)

[33mWarning[0m for LockedEther in contract 'modularLong':
    |// Contract Setup
    |
  > |contract modularLong is F3Devents {}
    |
    |contract DiviesCTR {
  at /home/jiaming/slither_fp_files/out14234.sol(122)


