Processing contract: /home/jiaming/slither_fp_files/out11458.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11458.sol:OtherRich3D
Processing contract: /home/jiaming/slither_fp_files/out11458.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out11458.sol:Rich3D
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11458.sol:Rich3DDatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11458.sol:Rich3DKeysCalc
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11458.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'NameFilter':
    | * NameFilter library
    | ***********************************************************/
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out11458.sol(117)

[33mWarning[0m for LockedEther in contract 'Rich3DDatasets':
    | * Rich3DDatasets library
    | ***********************************************************/
  > |library Rich3DDatasets {
    |    struct EventReturns {
    |        uint256 compressedData;
  at /home/jiaming/slither_fp_files/out11458.sol(195)

[33mWarning[0m for LockedEther in contract 'Rich3DKeysCalc':
    | * Rich3DKeysCalc library
    | ***********************************************************/
  > |library Rich3DKeysCalc {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out11458.sol(256)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | ***********************************************************/
  > | library SafeMath {
    |    /**
    |    * @dev Multiplies two numbers, throws on overflow.
  at /home/jiaming/slither_fp_files/out11458.sol(13)


