Processing contract: /home/jiaming/slither_fp_files/out13008.sol:HourglassInterface
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:J3DKeysCalcLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:J3Ddatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:J3Devents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:JIincForwarderInterface
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:JanKenPon
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:UintCompressor
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13008.sol:modularLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'J3DKeysCalcLong':
    |}
    |
  > |library J3DKeysCalcLong {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out13008.sol(1956)

[33mWarning[0m for LockedEther in contract 'J3Ddatasets':
    |
    |
  > |library J3Ddatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out13008.sol(2014)

[33mWarning[0m for LockedEther in contract 'J3Devents':
    | */
    |
  > |contract J3Devents {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out13008.sol(17)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |}
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out13008.sol(1880)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    |
    |
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out13008.sol(1726)

[33mWarning[0m for LockedEther in contract 'UintCompressor':
    |    }
    |}
  > |library UintCompressor {
    |    using SafeMath for *;
    |    
  at /home/jiaming/slither_fp_files/out13008.sol(1828)

[33mWarning[0m for LockedEther in contract 'modularLong':
    |}
    |
  > |contract modularLong is J3Devents {}
    |
    |interface JIincForwarderInterface {
  at /home/jiaming/slither_fp_files/out13008.sol(139)


