Processing contract: /home/jiaming/slither_fp_files/out13091.sol:ERC20
Processing contract: /home/jiaming/slither_fp_files/out13091.sol:NTech3DDatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13091.sol:NTech3DKeysCalcLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13091.sol:NTech3DLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13091.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out13091.sol:OtherNTech3D
Processing contract: /home/jiaming/slither_fp_files/out13091.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out13091.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'NTech3DDatasets':
    | * NTech3DDatasets library
    | ***********************************************************/
  > |library NTech3DDatasets {
    |    struct EventReturns {
    |        uint256 compressedData;
  at /home/jiaming/slither_fp_files/out13091.sol(195)

[33mWarning[0m for LockedEther in contract 'NTech3DKeysCalcLong':
    | * NTech3DKeysCalcLong library
    | ***********************************************************/
  > |library NTech3DKeysCalcLong {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out13091.sol(256)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    | * NameFilter library
    | ***********************************************************/
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out13091.sol(117)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | ***********************************************************/
  > | library SafeMath {
    |    /**
    |    * @dev Multiplies two numbers, throws on overflow.
  at /home/jiaming/slither_fp_files/out13091.sol(13)


