Processing contract: /home/jiaming/slither_fp_files/out12774.sol:CAE4DKeysCalcLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:CAE4Ddatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:CAE4Devents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:CAE4Dlong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:JIincForwarderInterface
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:UintCompressor
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out12774.sol:modularLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'CAE4DKeysCalcLong':
    |}
    |
  > |library CAE4DKeysCalcLong {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out12774.sol(1933)

[33mWarning[0m for LockedEther in contract 'CAE4Ddatasets':
    |contract modularLong is CAE4Devents {}
    |
  > |library CAE4Ddatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out12774.sol(126)

[33mWarning[0m for LockedEther in contract 'CAE4Devents':
    |pragma solidity ^0.4.24;
  > |contract CAE4Devents {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out12774.sol(2)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |}
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out12774.sol(1701)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    |}
    |
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out12774.sol(1777)

[33mWarning[0m for LockedEther in contract 'UintCompressor':
    |
    |
  > |library UintCompressor {
    |    using SafeMath for *;
    |    
  at /home/jiaming/slither_fp_files/out12774.sol(1881)

[33mWarning[0m for LockedEther in contract 'modularLong':
    |}
    |
  > |contract modularLong is CAE4Devents {}
    |
    |library CAE4Ddatasets {
  at /home/jiaming/slither_fp_files/out12774.sol(124)


