Processing contract: /home/jiaming/slither_fp_files/out11202.sol:DiviesInterface
Processing contract: /home/jiaming/slither_fp_files/out11202.sol:DiviesLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11202.sol:HourglassInterface
Processing contract: /home/jiaming/slither_fp_files/out11202.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11202.sol:UintCompressor
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out11202.sol(21)

[33mWarning[0m for LockedEther in contract 'UintCompressor':
    |// File: contracts/library/UintCompressor.sol
    |
  > |library UintCompressor {
    |    using SafeMath for *;
    |    
  at /home/jiaming/slither_fp_files/out11202.sol(126)


