Processing contract: /home/jiaming/slither_fp_files/out14934.sol:DiviesInterface
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:JIincForwarderInterface
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:MC2KeysCalcLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:MC2SettingInterface
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:MC2datasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:MC2events
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:MC2long
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:modularLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14934.sol:otherMC2
[33mWarning[0m for LockedEther in contract 'MC2KeysCalcLong':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library MC2KeysCalcLong {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out14934.sol(1657)

[33mWarning[0m for LockedEther in contract 'MC2datasets':
    |
    |
  > |library MC2datasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out14934.sol(1583)

[33mWarning[0m for LockedEther in contract 'MC2events':
    | */
    |
  > |contract MC2events {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out14934.sol(10)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out14934.sol(1752)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out14934.sol(1838)

[33mWarning[0m for LockedEther in contract 'modularLong':
    |
    |
  > |contract modularLong is MC2events {}
    |
    |contract MC2long is modularLong {
  at /home/jiaming/slither_fp_files/out14934.sol(124)


