Processing contract: /home/jiaming/slither_fp_files/out14838.sol:ERC20
Processing contract: /home/jiaming/slither_fp_files/out14838.sol:PresalePool
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14838.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14838.sol:WhiteList
[33mWarning[0m for LockedEther in contract 'SafeMath':
    |// written by @iamdefinitelyahuman
    |
  > |library SafeMath {
    |  function mul(uint256 a, uint256 b) internal pure returns (uint256) {
    |    if (a == 0) {
  at /home/jiaming/slither_fp_files/out14838.sol(6)


