Processing contract: /home/jiaming/slither_fp_files/out14653.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:PCKExtSettingInterface
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:PCKKeysCalcLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:PCKdatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:PCKevents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:PlayCoinGodInterface
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:PlayCoinKey
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:ProForwarderInterface
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14653.sol:modularKey
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'NameFilter':
    |
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out14653.sol(1867)

[33mWarning[0m for LockedEther in contract 'PCKKeysCalcLong':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library PCKKeysCalcLong {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out14653.sol(1772)

[33mWarning[0m for LockedEther in contract 'PCKdatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library PCKdatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out14653.sol(1698)

[33mWarning[0m for LockedEther in contract 'PCKevents':
    |//    (/_\/(/_| | | _\  .
    |//==============================================================================
  > |contract PCKevents {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out14653.sol(8)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out14653.sol(1953)

[33mWarning[0m for LockedEther in contract 'modularKey':
    |//====================================|=========================================
    |
  > |contract modularKey is PCKevents {}
    |
    |contract PlayCoinKey is modularKey {
  at /home/jiaming/slither_fp_files/out14653.sol(126)


