Processing contract: /home/jiaming/slither_fp_files/out11901.sol:KeysCalc
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11901.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11901.sol:POHCONTRACT
Processing contract: /home/jiaming/slither_fp_files/out11901.sol:POHMO
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11901.sol:POHMODATASETS
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11901.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out11901.sol:PoHEVENTS
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out11901.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'KeysCalc':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library KeysCalc {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out11901.sol(1494)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out11901.sol(1575)

[33mWarning[0m for LockedEther in contract 'POHMODATASETS':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library POHMODATASETS {
    |    
    |    struct EventReturns {
  at /home/jiaming/slither_fp_files/out11901.sol(1438)

[33mWarning[0m for LockedEther in contract 'PoHEVENTS':
    |pragma solidity ^0.4.24;
    |
  > |contract PoHEVENTS {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out11901.sol(3)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |
    |    /**
  at /home/jiaming/slither_fp_files/out11901.sol(1659)


