Processing contract: /home/jiaming/slither_fp_files/out14305.sol:F3DKeysCalcShort
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14305.sol:F3Ddatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14305.sol:F3Devents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14305.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14305.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out14305.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14305.sol:Snow
Processing contract: /home/jiaming/slither_fp_files/out14305.sol:SnowStorm
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out14305.sol:modularShort
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'F3DKeysCalcShort':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library F3DKeysCalcShort {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out14305.sol(1648)

[33mWarning[0m for LockedEther in contract 'F3Ddatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library F3Ddatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out14305.sol(1574)

[33mWarning[0m for LockedEther in contract 'F3Devents':
    |
    |
  > |contract F3Devents {
    |    // fired whenever a player registers a name
    |    event onNewName
  at /home/jiaming/slither_fp_files/out14305.sol(13)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out14305.sol(1722)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |
    |    /**
  at /home/jiaming/slither_fp_files/out14305.sol(1808)

[33mWarning[0m for LockedEther in contract 'modularShort':
    |}
    |
  > |contract modularShort is F3Devents {}
    |
    |contract SnowStorm is modularShort {
  at /home/jiaming/slither_fp_files/out14305.sol(126)


