Processing contract: /home/jiaming/slither_fp_files/out2234.sol:DataModal
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2234.sol:HourglassInterface
Processing contract: /home/jiaming/slither_fp_files/out2234.sol:Richer3D
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2234.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'DataModal':
    |}
    |
  > |library DataModal {
    |    struct PlayerInfo {
    |        uint256 inviteEarnings;
  at /home/jiaming/slither_fp_files/out2234.sol(494)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    |}
    |
  > |library SafeMath {
    |    /**
    |    * @dev Multiplies two numbers, throws on overflow.
  at /home/jiaming/slither_fp_files/out2234.sol(521)


