Processing contract: /home/jiaming/slither_fp_files/out2849.sol:H3DKeysCalcLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2849.sol:H3Ddatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2849.sol:H3Devents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2849.sol:Heaven3D
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2849.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2849.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out2849.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2849.sol:TeamDreamHubInterface
Processing contract: /home/jiaming/slither_fp_files/out2849.sol:modularLong
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'H3DKeysCalcLong':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library H3DKeysCalcLong {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out2849.sol(1893)

[33mWarning[0m for LockedEther in contract 'H3Ddatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library H3Ddatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out2849.sol(1823)

[33mWarning[0m for LockedEther in contract 'H3Devents':
    |//    (/_\/(/_| | | _\  .
    |//==============================================================================
  > |contract H3Devents {
    |	// fired whenever new decision is made
    |	event onNewDecision
  at /home/jiaming/slither_fp_files/out2849.sol(15)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |* @title -Name Filter- v0.1.9
    |*/
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out2849.sol(1972)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out2849.sol(2058)

[33mWarning[0m for LockedEther in contract 'modularLong':
    |//====================================|=========================================
    |
  > |contract modularLong is H3Devents {}
    |
    |contract Heaven3D is modularLong {
  at /home/jiaming/slither_fp_files/out2849.sol(156)


