Processing contract: /home/jiaming/slither_fp_files/out2075.sol:Datasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2075.sol:Events
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2075.sol:PT7D
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out2075.sol:ReferralInterface
Processing contract: /home/jiaming/slither_fp_files/out2075.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'Datasets':
    |}
    |
  > |library Datasets {
    |    struct Player {
    |        address addr;
  at /home/jiaming/slither_fp_files/out2075.sol(599)

[33mWarning[0m for LockedEther in contract 'Events':
    |pragma solidity ^0.4.23;
    |
  > |contract Events {
    |    event onActive();
    |
  at /home/jiaming/slither_fp_files/out2075.sol(3)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    |}
    |
  > |library SafeMath {
    |    function mul(uint256 a, uint256 b) 
    |        internal 
  at /home/jiaming/slither_fp_files/out2075.sol(618)


