Processing contract: /home/jiaming/slither_fp_files/out6294.sol:MFCoinsCalc
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6294.sol:MilAuthInterface
Processing contract: /home/jiaming/slither_fp_files/out6294.sol:MilFoldInterface
Processing contract: /home/jiaming/slither_fp_files/out6294.sol:Mildatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6294.sol:Milevents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6294.sol:Millionaire
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6294.sol:MillionaireInterface
Processing contract: /home/jiaming/slither_fp_files/out6294.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'MFCoinsCalc':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library MFCoinsCalc {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out6294.sol(835)

[33mWarning[0m for LockedEther in contract 'Mildatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library Mildatasets {
    |
    |    // between `DRAWN' and `ASSIGNED', someone need to claim winners.
  at /home/jiaming/slither_fp_files/out6294.sol(658)

[33mWarning[0m for LockedEther in contract 'Milevents':
    |}
    |
  > |contract Milevents {
    |
    |    // fired whenever a player registers
  at /home/jiaming/slither_fp_files/out6294.sol(26)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |
    |    /**
  at /home/jiaming/slither_fp_files/out6294.sol(720)


