Processing contract: /home/jiaming/slither_fp_files/out670.sol:EtherKnightGame
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out670.sol:HDX20Interface
Processing contract: /home/jiaming/slither_fp_files/out670.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out670.sol:SafeMath128
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'SafeMath':
    |
    |
  > |library SafeMath {
    |    
    |   
  at /home/jiaming/slither_fp_files/out670.sol(1403)

[33mWarning[0m for LockedEther in contract 'SafeMath128':
    |
    |
  > |library SafeMath128 {
    |    
    |   
  at /home/jiaming/slither_fp_files/out670.sol(1448)


