Processing contract: /home/jiaming/slither_fp_files/out6317.sol:FSBookInterface
Processing contract: /home/jiaming/slither_fp_files/out6317.sol:FSEvents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6317.sol:FSInterfaceForForwarder
Processing contract: /home/jiaming/slither_fp_files/out6317.sol:FSKeyCalc
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6317.sol:FSdatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6317.sol:FomoSport
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6317.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'FSEvents':
    |
    |/// @title Events used in FomoSport
  > |contract FSEvents {
    |
    |    event onGameCreated(
  at /home/jiaming/slither_fp_files/out6317.sol(4)

[33mWarning[0m for LockedEther in contract 'FSKeyCalc':
    |
    |// key calculation
  > |library FSKeyCalc {
    |    using SafeMath for *;
    |    
  at /home/jiaming/slither_fp_files/out6317.sol(846)

[33mWarning[0m for LockedEther in contract 'FSdatasets':
    |
    |// datasets
  > |library FSdatasets {
    |
    |    struct Game {
  at /home/jiaming/slither_fp_files/out6317.sol(899)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    |/// - changed asserts to requires with error log outputs
    |/// - removed div, its useless
  > |library SafeMath {
    |    
    |    /// @dev Multiplies two numbers, throws on overflow.
  at /home/jiaming/slither_fp_files/out6317.sol(981)


