Processing contract: /home/jiaming/slither_fp_files/out6864.sol:LDKeysCalc
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6864.sol:LDdatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6864.sol:MonkeyEvents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6864.sol:MonkeyScam
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6864.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6864.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out6864.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out6864.sol:modularMonkeyScam
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'LDKeysCalc':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library LDKeysCalc {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out6864.sol(1470)

[33mWarning[0m for LockedEther in contract 'LDdatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library LDdatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out6864.sol(1411)

[33mWarning[0m for LockedEther in contract 'MonkeyEvents':
    |pragma solidity ^0.4.24;
    |
  > |contract MonkeyEvents {
    |
    |    // fired whenever a player registers a name
  at /home/jiaming/slither_fp_files/out6864.sol(3)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |}
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out6864.sol(1539)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |
    |    /**
  at /home/jiaming/slither_fp_files/out6864.sol(1624)

[33mWarning[0m for LockedEther in contract 'modularMonkeyScam':
    |}
    |
  > |contract modularMonkeyScam is MonkeyEvents {}
    |
    |contract MonkeyScam is modularMonkeyScam {
  at /home/jiaming/slither_fp_files/out6864.sol(105)


