Processing contract: /home/jiaming/slither_fp_files/out7331.sol:AwardsTokensInterface
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:Buffer
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:CBOR
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:ERC20Interface
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:GAME
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:GameEventInterface
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:OraclizeAddrResolverI
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:OraclizeI
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out7331.sol:usingOraclize
  Attempt to decompile the contract with methods...
  Success. Inlining methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'Buffer':
    | */
    |
  > |library Buffer {
    |    struct buffer {
    |        bytes buf;
  at /home/jiaming/slither_fp_files/out7331.sol(44)

[33mWarning[0m for LockedEther in contract 'CBOR':
    |}
    |
  > |library CBOR {
    |    using Buffer for Buffer.buffer;
    |
  at /home/jiaming/slither_fp_files/out7331.sol(176)

[33mWarning[0m for LockedEther in contract 'GameEventInterface':
    |//////////////////////////////////////////////////////////////////////////////////////////////////////
    |
  > |contract GameEventInterface {
    |    event BuyTickets(address game, address to, uint amount);
    |    event Winner(address game, address to, uint prize, uint random_number, uint buyer_who_won);
  at /home/jiaming/slither_fp_files/out7331.sol(1243)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    |//////////////////////////////////////////////////////////////////////////////////////////////////////
    |
  > |library SafeMath {
    |    function add(uint a, uint b) internal pure returns (uint c) {
    |        c = a + b;
  at /home/jiaming/slither_fp_files/out7331.sol(1198)

[33mWarning[0m for LockedEther in contract 'usingOraclize':
    | */
    |
  > |contract usingOraclize {
    |    uint constant day = 60*60*24;
    |    uint constant week = 60*60*24*7;
  at /home/jiaming/slither_fp_files/out7331.sol(248)


