Processing contract: /home/jiaming/slither_fp_files/out9806.sol:DogInterfaceForForwarder
Processing contract: /home/jiaming/slither_fp_files/out9806.sol:DogScam
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out9806.sol:LDEvents
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out9806.sol:LDKeysCalc
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out9806.sol:LDdatasets
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out9806.sol:NameFilter
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out9806.sol:PlayerBookInterface
Processing contract: /home/jiaming/slither_fp_files/out9806.sol:SafeMath
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
Processing contract: /home/jiaming/slither_fp_files/out9806.sol:modularDogScam
  Attempt to decompile the contract with methods...
  Failed to decompile methods. Attempt to decompile the contract without identifying methods...
  Propagating constants...
  Verifying patterns...
[33mWarning[0m for LockedEther in contract 'LDEvents':
    |pragma solidity ^0.4.24;
    |
  > |contract LDEvents {
    |
    |    // fired whenever a player registers a name
  at /home/jiaming/slither_fp_files/out9806.sol(3)

[33mWarning[0m for LockedEther in contract 'LDKeysCalc':
    |//  |<(/_\/  (_(_||(_  .
    |//=======/======================================================================
  > |library LDKeysCalc {
    |    using SafeMath for *;
    |    /**
  at /home/jiaming/slither_fp_files/out9806.sol(1494)

[33mWarning[0m for LockedEther in contract 'LDdatasets':
    |//  _\ | | |_|(_ | _\  .
    |//==============================================================================
  > |library LDdatasets {
    |    //compressedData key
    |    // [76-33][32][31][30][29][28-18][17][16-6][5-3][2][1][0]
  at /home/jiaming/slither_fp_files/out9806.sol(1434)

[33mWarning[0m for LockedEther in contract 'NameFilter':
    |}
    |
  > |library NameFilter {
    |    /**
    |     * @dev filters name strings
  at /home/jiaming/slither_fp_files/out9806.sol(1566)

[33mWarning[0m for LockedEther in contract 'SafeMath':
    | * - removed div, its useless
    | */
  > |library SafeMath {
    |    
    |    /**
  at /home/jiaming/slither_fp_files/out9806.sol(1651)

[33mWarning[0m for LockedEther in contract 'modularDogScam':
    |}
    |
  > |contract modularDogScam is LDEvents {}
    |
    |contract DogScam is modularDogScam {
  at /home/jiaming/slither_fp_files/out9806.sol(105)


